---
# Copyright 2016, Ian Cordasco
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include: magnum_pre_install.yml
  tags:
    - magnum-install

- include: magnum_install.yml
  tags:
    - magnum-install

- include: magnum_post_install.yml
  tags:
    - magnum-config

- name: Run the systemd service role
  include_role:
    name: systemd_service
    private: true
  vars:
    systemd_user_name: "{{ magnum_system_user_name }}"
    systemd_group_name: "{{ magnum_system_group_name }}"
    systemd_tempd_prefix: openstack
    systemd_slice_name: magnum
    systemd_lock_path: /var/lock/magnum
    systemd_CPUAccounting: true
    systemd_BlockIOAccounting: true
    systemd_MemoryAccounting: true
    systemd_TasksAccounting: true
    systemd_services:
      - service_name: "{{ service_var.service_name }}"
        enabled: yes
        state: started
        execstarts: "{{ service_var.execstarts }}"
        execreloads: "{{ service_var.execreloads | default([]) }}"
        config_overrides: "{{ service_var.init_config_overrides }}"
  with_items: "{{ filtered_magnum_services }}"
  loop_control:
    loop_var: service_var
  tags:
    - magnum-config
    - systemd-service

- include: magnum_db_setup.yml
  when: inventory_hostname == groups['magnum_all'][0]
  tags:
    - magnum-config

- include: magnum_uwsgi.yml
  tags:
    - magnum-config

- include: magnum_service_setup.yml
  when: inventory_hostname == groups['magnum_all'][0]
  tags:
    - magnum-config

- name: Flush handlers
  meta: flush_handlers
